language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
env:
  - DJANGO_VERSION=">=1.8,<1.9"
  - DJANGO_VERSION=">=1.9,<1.10"
  - DJANGO_VERSION=">=1.10"
install:
  - pip install -q "Django${DJANGO_VERSION}"
  - pip install -q -e .
script:
  - python django_test_manage.py test django-dia
